[build-system]
requires = ["setuptools>=61.0.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

]
name = "nomad-combinatorial-thin-film"
description = "nomad image"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Paramesh Chandra", email = "paramesh.chandra@angstrom.uu.se" },
]
maintainers = [
    { name = "Paramesh Chandra", email = "paramesh.chandra@angstrom.uu.se" },
]
license = { file = "LICENSE" }
dependencies = [
    "nomad-lab>=1.4.1",
    "pandas",
    "numpy",
    "nomad-material-processing>=1.0.4",
    "nomad-measurements>=1.3.3",
    "fairmat-readers-xrd>=0.0.6",
    "httpx<0.28",
    "nomad-analysis>=0.0.7",
    "scikit-learn",
    "nomad-dtu-nanolab-plugin @ git+https://github.com/DTU-Nanolab-materials-discovery/nomad-dtu-nanolab-plugin.git@v0.4.18",
]

[project.urls]
Repository = "https://github.com/Automate-Solar/nomad-combinatorial-thin-film"

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "structlog",
    "mkdocs",
    "mkdocs-material>=9.0,<10",
    "pymdown-extensions",
    "mkdocs-click",
    "pytest-asyncio",
]

[tool.uv]
extra-index-url = [
  "https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple",
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # isort
    "I",
    # pylint
    "PL",
]

ignore = [
    "F403", # 'from module import *' used; unable to detect undefined names
    "PLC0415", # `import` should be at the top-level of a file
    "E501", # line too long
]

fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["PLC0415"] # import-outside-top-level

# this is entirely optional, you can remove this if you wish to
[tool.ruff.format]
# use single quotes for strings.
quote-style = "single"

# indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.'nomad.plugin']
hyperspectral_parser = "nomad_combinatorial_thin_film.parser:hyperspectral_parser_entry_point"
image_parser = "nomad_combinatorial_thin_film.parser:image_parser_entry_point"
image_schema = "nomad_combinatorial_thin_film.plugin:image_schema_package_entry_point"
hyperspectral_schema = "nomad_combinatorial_thin_film.plugin:hyperspectral_schema_package_entry_point"
sputtering_schema = "nomad_combinatorial_thin_film.plugin:sputtering_schema_package_entry_point"



[tool.cruft]
# Avoid updating workflow files, this leads to permissions issues
skip = [".github/*"]



